### ISSUE TITLE
magic-string@0.16.0 or later versions breaks buble

### ISSUE THREAD

**Issue by kzc** [Rich-Harris/magic-string#111]
[buble](https://gitlab.com/Rich-Harris/buble) works correctly with `magic-string@0.15.2`.

[buble](https://gitlab.com/Rich-Harris/buble) fails 41 tests with `magic-string@0.16.0`.

3f6dd4d64f9e255cbf995fc38675a3438b49c52b is the commit that breaks buble.

**Comment by kzc** [comment]
@Rich-Harris I recommend to leave `buble` with the older version of `magic-string` for now until the entire PR backlog is merged into `buble`.

**Comment by Rich-Harris** [comment]
@kzc Agree. Apologies I haven't been very responsive on that project recently – would be very happy to give you the commit bit if you'd like, just let me know

**Comment by kzc** [comment]
@Rich-Harris Thanks, but I'm good as a drive-by patcher for now. I am only using `buble` as a faster `babel 5` and it addresses the ES6 feature subset I need.

**Comment by kzc** [comment]
I think https://github.com/Rich-Harris/magic-string/commit/3f6dd4d64f9e255cbf995fc38675a3438b49c52b alters the magic-string move() behavior in some way. The destructuring transforms in particular use fairly complicated inserts, remove()s and moves()s and may rely on some unforeseen side effects of the previous implementation.

**Comment by adrianheine** [comment]
This can be closed now that you migrated bublé to `magic-string@^0.22.4`.
