### ISSUE TITLE
[question] How to translate variables to sourcemaps?

### ISSUE THREAD

**Issue by ericmackrodt** [Rich-Harris/magic-string#118]
Hi,

I'm trying to create the source maps for an xml type of language I'm converting to javascript and it works okay. The only thing I can't seem to be able to do is to be able to inspect the variables in the original source.
I use .overwrite to replace the variable name and, when I step through the code, I can't inspect the content of the variable.

Exemple:

Original:
`<whatever value="1">`

After MagicStings:
`const whateverVariable0 = 1;`

The process is:
remove '<'
overwrite 'whatever' with 'whateverVariable0'
remove value="
prepend  = before 1
remove ">

The sourcemaps work, I can step through it on Chrome, but when I hover "<whatever" to inspect it, nothing happens.

Any idea what I'm doing wrong?

Thanks.

**Comment by Rich-Harris** [comment]
Not sure I totally understand without being able to see an example, but have you tried passing `true` as the 4th argument to `overwrite`? That's an instruction to store the original content as a name, so that the segment in the sourcemap references `whatever`.

Another thing you *could* try is doing `generateMap({ hires: true })` — in theory it should be generating a segment for `whatever` -> `whateverVariable0` because of the edit, but maybe something is going wrong there...

**Comment by ericmackrodt** [comment]
Yeah, I tried those things, but no luck.
Okay, a bit more context, What I'm actually doing is converting HTML to javascript (I didn't say before because I didn't think it was that relevant), I gave that example because it's close enough and looked simple.

Sorry, I can't really post my code here because right now it's a bit rough and it's confusing out of context. You can take a look at the repo if you want though.
This is the file: [https://github.com/ericmackrodt/dasframeworken.js/blob/master/src/template.transpiler/transpiler.ts#L66](https://github.com/ericmackrodt/dasframeworken.js/blob/master/src/template.transpiler/transpiler.ts#L66)

But basically the logic is:

```
const ms = new MagicString('<div>', { filename: 'whatever.js' });
ms.remove(0, 1);
ms.overwrite(1, 4, 'div0', true);
ms.prependRight(1, 'const ');
ms.remove(4, 5);
ms.appendRight(4, ' = document.createElement('div');');
```

This works, the code is converted, I can put breakpoints in the code and chrome stops on them but, if I hover `div` on chrome, nothing comes up, it's supposed to show the object for the html element.

**Comment by ericmackrodt** [comment]
So, I was reading more about sourcemaps and it turns out that, if you change the name of the variable, it gets lost. It's a normal behavior. It happens when you create sourcemaps for minified code as well.

**Comment by mourner** [comment]
Closing — I assume you've found the answer and there's nothing actionable on the magic-string side, right?
