### ISSUE TITLE
Feature request: inputSourceMap option

### ISSUE THREAD

**Issue by droooney** [Rich-Harris/magic-string#123]
As far as I understand, for now it's not possible to pass an input sourcemap to the constructor in order to get it modified by the library and return the modified version.

**Comment by Rich-Harris** [comment]
See https://github.com/rich-harris/sorcery — it's a bad idea for transformers to have to worry about other people's sourcemaps rather than just generating their own, much better to have a tool that's responsible for composing them

**Comment by droooney** [comment]
Seems reasonable, thank you!

PS: some transformers do exactly that, i.e. babel or UglifyJS.
