### ISSUE TITLE
Input source maps?

### ISSUE THREAD

**Issue by whaaaley** [Rich-Harris/magic-string#140]
I thought this might be a good tool to insert CSS into a JS bundle. It works great, except that I loose the source map to my CSS. Is it within the scope of this project to allow input source maps so that when in use `overwrite` to insert CSS, it maps to both the JS and the CSS source?

**Comment by aleclarson** [comment]
Are you converting the CSS to JS before bundling? You should be, and that transformation should have its own source map.

I assume you're using `MagicString.Bundle`, yes? I agree that it should support input source maps, which would allow you to map back to the CSS properly.

I was hoping [sorcery](https://github.com/Rich-Harris/sorcery) would do the trick, but it looks like we'll need a specialized solution for bundling.

**Comment by whaaaley** [comment]
> Are you converting the CSS to JS before bundling? You should be, and that transformation should have its own source map.

I am not. I just want the CSS to be a string. I am going from SCSS to CSS and I do have a sourcemap for that.

I also tried sorcery in many different ways but I couldn't' get it to work either. I'm glad you're looking into this! :D

**Comment by aleclarson** [comment]
Mozilla's [source-map][1] library has [`applySourceMap`][2], but that has [the same problem[3]. :)

I have a working solution, but it needs more tests and there's probably a bug or two. I will link it once I've tested it a little more. :)

[1]: https://github.com/mozilla/source-map
[2]: https://github.com/mozilla/source-map#sourcemapgeneratorprototypeapplysourcemapsourcemapconsumer-sourcefile-sourcemappath
[3]: https://github.com/mozilla/source-map/issues/216

**Comment by aleclarson** [comment]
More details [here](https://github.com/aleclarson/sorcery/issues/1).  🎉
