### ISSUE TITLE
How do I exchange two ranges?

### ISSUE THREAD

**Issue by eight04** [Rich-Harris/magic-string#141]
For example, I want to transform `foo-bar` to `bar-foo`. I've tried using `.move` but the `bar` chunk is lost:
```js
const MagicString = require("magic-string");
const s = new MagicString("foo-bar");
s.move(0, 3, 7);
s.move(4, 7, 0);
console.log(s.toString()); // "-foo"
```
Using `move()` does work when two ranges are concatenated:
```js
const MagicString = require("magic-string");
const s = new MagicString("foobar");
s.move(0, 3, 6);
s.move(3, 6, 0);
console.log(s.toString()); // "barfoo"
```
But then another problem is that I can't insert text between two ranges. It would be moved together.
```js
const MagicString = require("magic-string");
const s = new MagicString("foobar");
s.move(0, 3, 6);
s.move(3, 6, 0);
s.appendRight(3, "-");
console.log(s.toString()); // "-barfoo"
```

**Comment by alangpierce** [comment]
There may be a way to get it working with `move`, but I've generally found that magic-string tends to break down when dealing with complex interactions of changes (many of which would have unclear behavior even to a human), so you may want to use simpler operations. [decaffeinate](https://github.com/decaffeinate/decaffeinate) uses magic-string for all of its transforms, and it only uses `appendLeft`, `overwrite`, and `remove` (except in one fragile-but-necessary case where it uses `prependLeft`).

I've managed to avoid a lot of trouble by following some basic rules:
* Always remove before adding.
* Always perform inserts left-to-right.

Also note that, depending on context, swapping two ranges can also be seen as taking the thing on the left and moving it to the right, or vice versa. Sometimes it's easier to keep one side still and only operate on the rest.

**Comment by eight04** [comment]
> Also note that, depending on context, swapping two ranges can also be seen as taking the thing on the left and moving it to the right, or vice versa. Sometimes it's easier to keep one side still and only operate on the rest.

Thanks for the advice. It works properly if it only moves forward:
```js
const MagicString = require("magic-string");
const s = new MagicString("foo-bar");
s.move(3, 4, 7); // move the separator "-" to the end
s.move(0, 3, 7); // move "foo" to the end
console.log(s.toString()); // "bar-foo"
```
If you want to insert a separator:
```js
const MagicString = require("magic-string");
const s = new MagicString("foobar");
s.appendLeft(6, "-"); // append separator "-" to the end
s.move(0, 3, 6); // move "foo" to the end
console.log(s.toString()); // "bar-foo"
```
