### ISSUE TITLE
Bundle mappings and source mutation

### ISSUE THREAD

**Issue by aleclarson** [Rich-Harris/magic-string#146]
Does the `generateMap` method of `MagicString.Bundle` ignore changes made to any of the `MagicString` instances added via `addSource`? In other words, do I need to rewrap sources before passing them?

```js
const source = new MagicString('...');
source.append('...');

// Can I do this?
bundle.addSource({ filename: 'foo.js', content: source });

// Or do I need to do this?
bundle.addSource({
  filename: 'foo.js',
  content: new MagicString(source.toString()),
});
```

The first way would be ideal. :)

Also, the bundle's sourcemap should map back to the original source, not the mutated source.

**Comment by aleclarson** [comment]
Looking at [the code](https://github.com/Rich-Harris/magic-string/blob/master/src/Bundle.js#L97-L142), it seems to do what I want. 🎉

**Comment by mourner** [comment]
👍
