### ISSUE TITLE
Just a tiny question, Why you put the property "module" at package.json?

### ISSUE THREAD

**Issue by simaodeveloper** [Rich-Harris/magic-string#151]
I don't found any reference about property called "module" at package.json root on NPM documentation.

Can you explain to me how this works?

example:

```
"module": "dist/magic-string.es.js",
```

**Comment by mourner** [comment]
It exposes the package as a ES module.
https://github.com/rollup/rollup/wiki/pkg.module
https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/
