### ISSUE TITLE
Advice for appendLeft() vs. appendRight().

### ISSUE THREAD

**Issue by jdalton** [Rich-Harris/magic-string#153]
Could you provide an example or guidance for when `appendLeft()` and `appendRight()` should be used. I'm not sure which situations I should use one or the other.

**Comment by alangpierce** [comment]
Hey @jdalton! I wrote up some advice in https://github.com/Rich-Harris/magic-string/issues/109#issuecomment-261741167 that you might find useful.

If you have relatively few operations that you're doing, then it may be convenient to take advantage of the fact that `appendLeft` things will always be to the left of `appendRight` things, and that if you intend to call `move` or `slice`, you'll keep `appendLeft` things but not `appendRight` things, in case you want to include/exclude recently-inserted parens, for example. But for more complex cases, my experience is that the system breaks down and it's best to always do `appendLeft` and to be careful to do all the operations in left-to-right order.

**Comment by jdalton** [comment]
Thank you @alangpierce!
