### ISSUE TITLE
Missing LICENSE file in release tarball.

### ISSUE THREAD

**Issue by ericsnowcurrently** [Rich-Harris/magic-string#157]
I found your `LICENSE` file at top of the repo.  However, there is no `LICENSE` file in the release tarball (under https://registry.npmjs.org/).  There should be.

**Comment by mourner** [comment]
I just checked — there is a LICENSE file in the release tarballs.

**Comment by ericsnowcurrently** [comment]
My apologies.  Apparently we're pinned to 0.22.5.
