### ISSUE TITLE
Wrong columns on source indented with spaces

### ISSUE THREAD

**Issue by dmail** [Rich-Harris/magic-string#210]
When the source string passed to magic string is indented with spaces the generated mappings will map back to column 0. I would expect to be able to map back to the right column (in example below column 3)

```js
import { createRequire } from "node:module"
import MagicString from "magic-string"

const require = createRequire(import.meta.url)
const { SourceMapConsumer } = require("source-map")

const source = `
  a
`
const magicString = new MagicString(source)
magicString.overwrite(source.indexOf("a"), source.indexOf("a") + 1, "b")
const output = magicString.toString()
const map = magicString.generateMap({ hires: true })
const sourceMapConsumer = await new SourceMapConsumer(map)
const originalPosition = sourceMapConsumer.originalPositionFor({
  line: 1,
  column: 3,
})
console.log({ output, originalPosition })
```

Executing code above logs the following:

```console
{
  output: '\n  b\n',
  originalPosition: { source: 'null', line: 1, column: 0, name: null }
}
```

I am surprised to get `column: 0`. I would expect `column: 3`. Is it a "bug" in magic-string?

**Comment by sapphi-red** [comment]
I don't think this is a bug.
`{ line: 1, column: 3 }` points to nothing for `input`. (Note that there's a line break in the first line.)
If you want to point the "a", it should be `{ line: 2, column: 3 }`.

**Comment by dmail** [comment]
Indeed, will retry with the right values

**Comment by dmail** [comment]
And with the right values it works as expected, thank you
