### ISSUE TITLE
[Feature request] Add method to restore previously removed range

### ISSUE THREAD

**Issue by aleclarson** [Rich-Harris/magic-string#218]
```ts
const string = new MagicString("abcd")

string.remove(0, 3)
string.toString() // => "d"

// ...later on...
string.restore(2, 3)
string.toString() // => "cd"
```

**Comment by aleclarson** [comment]
**Why not just add the removed range with existing methods?**
Because I wouldn't be able to insert new content into the restored range.

Example: https://stackblitz.com/edit/node-1gmfpo?file=index.js

**Comment by antfu** [comment]
That makes sense to me. PR welcome :)

**Comment by KermanX** [comment]
I opened https://github.com/Rich-Harris/magic-string/pull/271 for this feature.

The method introduced in that PR is `reset`, rather than `restore`, because of its actual behavior
