### ISSUE TITLE
Add support for `x_google_ignoreList`

### ISSUE THREAD

**Issue by bmeurer** [Rich-Harris/magic-string#241]
`magic-string` is used throughout various parts of the JavaScript ecosystem that deal with generating and manipulating source maps. Having basic support for the new `x_google_ignoreList` source map extension[^1][^2] will make it easy and natural for tools to mark library / framework code as ignore-listed (for debuggers).

Doc: https://goo.gle/devtools-ignoreList-adoption

[^1]: https://developer.chrome.com/blog/devtools-better-angular-debugging
[^2]: https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.mt2g20loc2ct

**Comment by antfu** [comment]
Close as it's shipped 🎉

**Comment by bmeurer** [comment]
Only the initial support landed. As proposed in the doc, for easier adoption, a second follow up PR should land (which I'm preparing) to add support for marking sources as ignore listed when adding to bundles.
