### ISSUE TITLE
sourcemap-codec is deprecated

### ISSUE THREAD

**Issue by zdm** [Rich-Harris/magic-string#245]
```
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

Could you, please, update it?

**Comment by antfu** [comment]
https://github.com/Rich-Harris/magic-string/blob/34935df2d22cee89f6bdadf8503d9a31602393bd/package.json#L63

**Comment by zdm** [comment]
Could you please release version `1.0.0`?
It is recommended to use version 1.0.0 when you releasing first public stable release.
Using version 0.x.x leading to the confuses, because npm skips leading zeros in the version number.
