### ISSUE TITLE
service worker should be supported

### ISSUE THREAD

**Issue by loynoir** [Rich-Harris/magic-string#258]
### Env

service worker

### Detail

```js
> JSON.stringify([typeof window, typeof Buffer, typeof btoa, typeof self, typeof self.btoa, typeof globalThis.btoa])
 '["undefined","undefined","function","object","function","function"]' 
```

### Actual

Got Error.

Unsupported environment: `window.btoa` or `Buffer` should be supported

### Expected

service worker should be supported

**Comment by loynoir** [comment]
@antfu 

Given

-  `node` also have `btoa`

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/05094b6df4fb6f4404333725f13d63dd8aabeb34/types/node/buffer.d.ts#L2328-L2330

I suggest check `Buffer` first

```js
if (typeof Buffer === "function") {
  // ...
} else if (typeof btoa === "function") {
  // ...
}
```

**Comment by curran** [comment]
It still fails as this logic was not updated:

https://github.com/Rich-Harris/magic-string/blob/master/src/SourceMap.js#L3
