### ISSUE TITLE
Feat: add offfset option to support Vue SFC

### ISSUE THREAD

**Issue by zhiyuanzmj** [Rich-Harris/magic-string#296]
In [jsx-directive](https://github.com/vue-macros/vue-macros/blob/main/packages/jsx-directive/src/core/index.ts) I want to support vue-sfc. but must manual add offfset for every api. So can we provide a `offset` field to add it automatic.

### Before
```tsx
const { script, scriptSetup } = parseSFC(code, id)

s.appendLeft(node.start! + script.loc.start.offset, '....')
s.appendLeft(node.start! + scriptSetup.loc.start.offset, '....')
```

### After
```tsx
let asts: { ast: Program, offset: number }[] = []
const { scriptSetup, getSetupAst, script, getScriptAst } = parseSFC(code,id)
if (script) {
  asts.push({ ast: getScriptAst()!, offset: script.loc.start.offset })
}
if (scriptSetup) {
  asts.push({ ast: getSetupAst()!, offset: scriptSetup.loc.start.offset })
}

const s = new MagicStringAST(code, { offset: 0 })
for (const { ast, offset } of asts) {
  s.offset = offset
  //  ^ can be modified.
  s.appendLeft(node.start, '....')
}
```

I have been implement it in [magic-string-ast](https://github.com/sxzz/magic-string-ast/pull/50/files).
but @sxzz said this feature better to implement in magic-string, So can i do it?

**Comment by antfu** [comment]
I wonder if it would be be better to create a new proxy instance like `const s2 = s.withOffset(10)` or could do chain pipeline like `s.withOffset(10).appendLeft(node.start)`
