### ISSUE TITLE
Best practice for controlling order of multiple insertions at one position

### ISSUE THREAD

**Issue by eventualbuddha** [Rich-Harris/magic-string#7]
In building decaffeinate I've run into an issue where the order of strings inserted at the same position is not always what I'd like it to be. For example, given the CoffeeScript string `a b: c` I'd like to turn it into the JavaScript string `a({b: c});`. This might be accomplished by visiting various AST node types in turn and inserting or replacing characters as required. Here's an example:

```
REPLACE 1...2 "("
INSERT 6 ")"
INSERT 2 "{"
INSERT 6 "}"
INSERT 6 ";"
```

This would be represented using MagicString's API like so:

```js
> new MagicString('a b: c').replace(1, 2, '(').insert(6, ')').insert(2, '{').insert(6, '}').insert(6, ';').toString()
'a({b: c)};'
```

As you can see, the resulting string is not correct. Do you have any suggestions for achieving the desired result here? I'm not tied to the sequence of API calls above.

**Comment by Rich-Harris** [comment]
This is tricky - transpiling CoffeeScript probably just straddles the border between what MagicString is designed for and what it can't do (i.e. plumbing the depths of an AST and handling the children of already-handled nodes).

If there was an API like this...

```js
new MagicString('a b: c')
  .replace(1, 2, '(')
  .insert(6, ')')
  .insert(2, '{', true)
  .insert(6, '}')
  .insert(6, ';', true)
  .toString()
```

...where the third `true` argument to `insert` meant 'insert *after* any previous insertions at this location, would decaffeinate be able to know when to use it (e.g. based on whether we're entering or leaving a node - I haven't read the decaffeinate source yet so have no idea how it works!)? I'm not immediately sure how it would be implemented by MagicString, but it feels doable.

**Comment by eventualbuddha** [comment]
The current behavior of insert will insert subsequent strings after any previous strings, so a flag would probably flip that to before instead.

That said, I feel like what you're saying about inserting on node enter and node leave separately is probably the correct approach. That way I should be able to ensure that the insertions happen in source order, i.e 

```
Enter FunctionApplication, REPLACE (
Enter ObjectInitialiser INSERT {
Leave ObjectInitialiser INSERT }
Leave FunctionApplication INSERT );
``` 

I'll try that and report back. Thanks for the suggestion!

**Comment by eventualbuddha** [comment]
I didn't have to go quite that far to fix the issue I was seeing, though I may eventually need to for other examples. Here's the fix for `Ember = require "ember"`, which was turning into `var Ember = require("ember";)`: https://github.com/eventualbuddha/decaffeinate/commit/4456feae6d1e801e047436cf809bd777afb0606f

**Comment by Rich-Harris** [comment]
Ah, that's a neat trick! Am reading [utils/traverse.js](https://github.com/eventualbuddha/decaffeinate/blob/master/src/utils/traverse.js) and wondering why anybody would ever need estraverse
