### ISSUE TITLE
Flow type annotations?

### ISSUE THREAD

**Issue by eventualbuddha** [Rich-Harris/magic-string#75]
Any interest in distributing flow type declarations with the package? I'm trying to get everything under decaffeinate type checked, and this would help. I could also just add it to flow-typed. It would require updating the file when the external API changes.

**Comment by eventualbuddha** [comment]
Just went ahead and did this: https://github.com/flowtype/flow-typed/pull/148

**Comment by mourner** [comment]
The module now maintains [TypeScript definitions](https://github.com/Rich-Harris/magic-string/blob/master/index.d.ts). Flow definitions are still welcome though — feel free to work on a PR to `flow-typed`.
